
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 3: Install dependencies and build the project
    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build

    # 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./venellinus1/vv-portfolio
      node-version: '20'  
